### PR TITLE
Fix ID validation Belgium.

### LINKED ISSUE #82: [v1.3.0] Incorrect ID validation for Belgium.
Related to #75, I see some problems with the current implementation:

- It does not allow 00 as day or 00 as month while the docs specify that it is allowed for people whose day/month of birth was unknown at the time of registration.
- Digits 7-9 represent a sequence number that ranges from 001 to 998 (both inclusive) so values 000 and 999 are invalid. The current implementation does not seem to check this.

See https://github.com/reducktion/socrates-java/pull/36/files for an implementation in the Java fork that does take these things into account.

I'm up for fixing it if you want, please confirm.

### PR DESCRIPTION
**Pull request by YvesBos**
Fixes #82  .

Changes:

- added sequence number validation (valid range is 001 - 998)
- 00 as day or 00 as month is now also valid
- allow for spaces in ID number

Included additional tests to test the changes.

### CODE REVIEW

**Review by JoaoFSCruz — APPROVED** [review]
Great job! Nothing like receiving a contribution from a local 😅 

Just let @AlexOlival review it and it's good to go!

Thank you for your contribution 🙏

**Comment by AlexOlival** [comment]
@all-contributors please add @YvesBos for code

**Comment by AlexOlival** [comment]
Thank you man :pray:

**Comment by AlexOlival** [comment]
@all-contributors please add @YvesBos for bugs

**Pull request merged**
